#!/bin/sh
xclock -geometry -0+0 -digital -update 1 -fn fixed -sharp &
/usr/home/murt/online/my_github/teonho/freebsd/my_conf/xdm/shutdown3.sh &
xconsole -geometry 480x130-0-0 -daemon -notify -verbose -fn fixed -exitOnFail
